# Generated by Django 5.2.1 on 2025-05-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("push_agreement", models.BooleanField(default=False)),
                ("push_token", models.CharField(blank=True, max_length=255, null=True)),
                ("estimated_birth", models.DateField(blank=True, null=True)),
                (
                    "classification",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("status", models.CharField(default="unconfirmed", max_length=50)),
                ("access_token", models.CharField(default="0", max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
