# Generated by Django 5.2.1 on 2025-05-12 21:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yoldot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user_data",
        ),
    ]
