# Generated by Django 5.2.1 on 2025-05-12 21:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoldot", "0002_alter_user_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="classification",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="estimated_birth",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="push_token",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(default="unconfirmed", max_length=256),
        ),
    ]
