# Generated by Django 5.2.1 on 2025-05-12 22:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("yoldot", "0003_alter_user_classification_alter_user_email_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"managed": False},
        ),
    ]
