# Generated by Django 5.2.1 on 2025-05-14 11:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoldot", "0004_alter_user_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashvaa",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("category", models.CharField(max_length=25)),
                ("title", models.CharField(max_length=128)),
                ("איכילוב", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "תל_השומר_שיבא",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("לניאדו", models.CharField(blank=True, max_length=512, null=True)),
                ("מאיר", models.CharField(blank=True, max_length=512, null=True)),
                ("קפלן", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "מעייני_הישועה",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("אסף_הרופא", models.CharField(blank=True, max_length=512, null=True)),
                ("וולפסון", models.CharField(blank=True, max_length=512, null=True)),
                ("בלינסון", models.CharField(blank=True, max_length=512, null=True)),
                ("עין_כרם", models.CharField(blank=True, max_length=512, null=True)),
                ("שערי_צדק", models.CharField(blank=True, max_length=512, null=True)),
                ("הר_הצופים", models.CharField(blank=True, max_length=512, null=True)),
                ("סנט_ג_וזף", models.CharField(blank=True, max_length=512, null=True)),
                ("אסותא", models.CharField(blank=True, max_length=512, null=True)),
                ("ברזילי", models.CharField(blank=True, max_length=512, null=True)),
                ("סורוקה", models.CharField(blank=True, max_length=512, null=True)),
                ("יוספטל", models.CharField(blank=True, max_length=512, null=True)),
                ("הלל_יפה", models.CharField(blank=True, max_length=512, null=True)),
                ("העמק", models.CharField(blank=True, max_length=512, null=True)),
                ("פוריה", models.CharField(blank=True, max_length=512, null=True)),
                ("זיו", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "המרכז_הרפואי_לגליל",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("רמב_ם", models.CharField(blank=True, max_length=512, null=True)),
                (
                    "בני_ציון_רוטשילד",
                    models.CharField(blank=True, max_length=512, null=True),
                ),
                ("כרמל", models.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                "db_table": "compare",
                "managed": False,
            },
        ),
    ]
