# Generated by Django 5.2.1 on 2025-05-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoldot", "0005_hashvaa"),
    ]

    operations = [
        migrations.CreateModel(
            name="Survey",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "תאריך_הלידה",
                    models.CharField(
                        db_column="תאריך הלידה",
                        max_length=10,
                        verbose_name="תאריך הלידה",
                    ),
                ),
                (
                    "מקום_לידה",
                    models.CharField(
                        db_column="מקום לידה", max_length=64, verbose_name="מקום לידה"
                    ),
                ),
                (
                    "מספר_לידה",
                    models.CharField(
                        db_column="מספר לידה", max_length=2, verbose_name="מספר לידה"
                    ),
                ),
                (
                    "הריון_בסיכון",
                    models.CharField(
                        db_column="הריון בסיכון",
                        max_length=2,
                        verbose_name="הריון בסיכון",
                    ),
                ),
                (
                    "סיכון_פירוט",
                    models.CharField(
                        db_column="סיכון פירוט",
                        max_length=300,
                        verbose_name="סיכון פירוט",
                    ),
                ),
                (
                    "התערבויות",
                    models.CharField(
                        db_column="התערבויות", max_length=128, verbose_name="התערבויות"
                    ),
                ),
                (
                    "קיסרי_חירום",
                    models.CharField(
                        db_column="קיסרי חירום",
                        max_length=64,
                        verbose_name="קיסרי חירום",
                    ),
                ),
                (
                    "סוגי_זירוז",
                    models.CharField(
                        db_column="סוגי זירוז",
                        max_length=128,
                        verbose_name="סוגי זירוז",
                    ),
                ),
                (
                    "לווי_מיילדת",
                    models.CharField(
                        db_column="לווי מיילדת",
                        max_length=64,
                        verbose_name="לווי מיילדת",
                    ),
                ),
                (
                    "לווי_נוסף",
                    models.CharField(
                        db_column="לווי נוסף", max_length=64, verbose_name="לווי נוסף"
                    ),
                ),
                (
                    "כבוד",
                    models.CharField(
                        db_column="כבוד", max_length=1, verbose_name="כבוד"
                    ),
                ),
                (
                    "פרטיות_כללי",
                    models.CharField(
                        db_column="פרטיות כללי",
                        max_length=1,
                        verbose_name="פרטיות כללי",
                    ),
                ),
                (
                    "סגירת_דלת",
                    models.CharField(
                        db_column="סגירת דלת", max_length=64, verbose_name="סגירת דלת"
                    ),
                ),
                (
                    "סביבה_שקטה",
                    models.CharField(
                        db_column="סביבה שקטה", max_length=1, verbose_name="סביבה שקטה"
                    ),
                ),
                (
                    "דפיקה_בדלת",
                    models.CharField(
                        db_column="דפיקה בדלת", max_length=20, verbose_name="דפיקה בדלת"
                    ),
                ),
                (
                    "שרותים_ומקלחת",
                    models.CharField(
                        db_column="שרותים ומקלחת",
                        max_length=2,
                        verbose_name="שרותים ומקלחת",
                    ),
                ),
                (
                    "חיסיון_רפואי_אישי",
                    models.CharField(
                        db_column="חיסיון רפואי אישי",
                        max_length=1,
                        verbose_name="חיסיון רפואי אישי",
                    ),
                ),
                (
                    "חיסיון_רפואי_של_הסובבות",
                    models.CharField(
                        db_column="חיסיון רפואי של הסובבות",
                        max_length=1,
                        verbose_name="חיסיון רפואי של הסובבות",
                    ),
                ),
                (
                    "הסבר_סיכונים_סיכויים_חלופות",
                    models.CharField(
                        db_column="הסבר סיכונים סיכויים חלופות",
                        max_length=1,
                        verbose_name="הסבר סיכונים סיכויים חלופות",
                    ),
                ),
                (
                    "איום_והפחדה",
                    models.CharField(
                        db_column="איום והפחדה",
                        max_length=2,
                        verbose_name="איום והפחדה",
                    ),
                ),
                (
                    "קבלת_החלטות",
                    models.CharField(
                        db_column="קבלת החלטות",
                        max_length=1,
                        verbose_name="קבלת החלטות",
                    ),
                ),
                (
                    "כבוד_לבקשות_היולדת",
                    models.CharField(
                        db_column="כבוד לבקשות היולדת",
                        max_length=1,
                        verbose_name="כבוד לבקשות היולדת",
                    ),
                ),
                (
                    "התייחסות_לרצונות",
                    models.CharField(
                        db_column="התייחסות לרצונות",
                        max_length=1,
                        verbose_name="התייחסות לרצונות",
                    ),
                ),
                (
                    "סירוב_לטיפול",
                    models.CharField(
                        db_column="סירוב לטיפול",
                        max_length=2,
                        verbose_name="סירוב לטיפול",
                    ),
                ),
                (
                    "כיבוד_סירוב_לטיפול",
                    models.CharField(
                        db_column="כיבוד סירוב לטיפול",
                        max_length=2,
                        verbose_name="כיבוד סירוב לטיפול",
                    ),
                ),
                (
                    "תמיכה_רציפה",
                    models.CharField(
                        db_column="תמיכה רציפה",
                        max_length=1,
                        verbose_name="תמיכה רציפה",
                    ),
                ),
                (
                    "תקשורת_אפקטיבית",
                    models.CharField(
                        db_column="תקשורת אפקטיבית",
                        max_length=1,
                        verbose_name="תקשורת אפקטיבית",
                    ),
                ),
                (
                    "עידוד_לתנועה",
                    models.CharField(
                        db_column="עידוד לתנועה",
                        max_length=2,
                        verbose_name="עידוד לתנועה",
                    ),
                ),
                (
                    "אוכל_ושתיה",
                    models.CharField(
                        db_column="אוכל ושתיה", max_length=24, verbose_name="אוכל ושתיה"
                    ),
                ),
                (
                    "שיכוך_כאבים",
                    models.CharField(
                        db_column="שיכוך כאבים",
                        max_length=2,
                        verbose_name="שיכוך כאבים",
                    ),
                ),
                (
                    "הצעות_שיכוך_כאבים",
                    models.CharField(
                        db_column="הצעות שיכוך כאבים",
                        max_length=256,
                        verbose_name="הצעות שיכוך כאבים",
                    ),
                ),
                (
                    "שלב_שני",
                    models.CharField(
                        db_column="שלב שני", max_length=2, verbose_name="שלב שני"
                    ),
                ),
                (
                    "תנוחות_לידה",
                    models.CharField(
                        db_column="תנוחות לידה",
                        max_length=64,
                        verbose_name="תנוחות לידה",
                    ),
                ),
                (
                    "תנוחה_מועדפת",
                    models.CharField(
                        db_column="תנוחה מועדפת",
                        max_length=2,
                        verbose_name="תנוחה מועדפת",
                    ),
                ),
                (
                    "תחושת_דחף",
                    models.CharField(
                        db_column="תחושת דחף", max_length=2, verbose_name="תחושת דחף"
                    ),
                ),
                (
                    "תמיכה_בפרניאום",
                    models.CharField(
                        db_column="תמיכה בפרניאום",
                        max_length=64,
                        verbose_name="תמיכה בפרניאום",
                    ),
                ),
                (
                    "קרייסטלר",
                    models.CharField(
                        db_column="קרייסטלר", max_length=2, verbose_name="קרייסטלר"
                    ),
                ),
                (
                    "עור_לעור",
                    models.CharField(
                        db_column="עור לעור", max_length=2, verbose_name="עור לעור"
                    ),
                ),
                (
                    "הצמדה_לחזה",
                    models.CharField(
                        db_column="הצמדה לחזה", max_length=2, verbose_name="הצמדה לחזה"
                    ),
                ),
                (
                    "רחצת_תינוק",
                    models.CharField(
                        db_column="רחצת תינוק/ת",
                        max_length=2,
                        verbose_name="רחצת תינוק/ת",
                    ),
                ),
                (
                    "הפרדת_אם_ותינוק",
                    models.CharField(
                        db_column="הפרדת אם ותינוק/ת",
                        max_length=2,
                        verbose_name="הפרדת אם ותינוק/ת",
                    ),
                ),
                (
                    "סיבת_הפרדה",
                    models.CharField(
                        db_column="סיבת הפרדה", max_length=12, verbose_name="סיבת הפרדה"
                    ),
                ),
                (
                    "סיבה_אחרת_להפרדה",
                    models.CharField(
                        db_column="סיבה אחרת להפרדה",
                        max_length=500,
                        verbose_name="סיבה אחרת להפרדה",
                    ),
                ),
                (
                    "ביות_מלא",
                    models.CharField(
                        db_column="ביות מלא", max_length=2, verbose_name="ביות מלא"
                    ),
                ),
                (
                    "שביעות_רצון",
                    models.CharField(
                        db_column="שביעות רצון",
                        max_length=1,
                        verbose_name="שביעות רצון",
                    ),
                ),
                (
                    "TAGS",
                    models.CharField(
                        db_column="TAGS", max_length=600, verbose_name="TAGS"
                    ),
                ),
                (
                    "תיאור_סיפור_לידה",
                    models.CharField(
                        db_column="תיאור סיפור לידה",
                        max_length=10000,
                        verbose_name="תיאור סיפור לידה",
                    ),
                ),
                (
                    "הערות",
                    models.CharField(
                        db_column="הערות", max_length=4000, verbose_name="הערות"
                    ),
                ),
                (
                    "Entry_Date",
                    models.CharField(
                        db_column="Entry Date", max_length=64, verbose_name="Entry Date"
                    ),
                ),
                (
                    "אימייל",
                    models.CharField(
                        db_column="אימייל", max_length=64, verbose_name="אימייל"
                    ),
                ),
                ("is_checked", models.IntegerField(verbose_name="is_checked")),
            ],
            options={
                "db_table": "survey_results",
                "managed": False,
            },
        ),
    ]
