# Generated by Django 5.2.1 on 2025-05-17 21:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoldot", "0006_survey"),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("logo", models.CharField(blank=True, max_length=255, null=True)),
                ("image", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "provider_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "provider_email",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                (
                    "provider_link",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                ("available_coupons", models.IntegerField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "description_extended",
                    models.CharField(blank=True, max_length=3000, null=True),
                ),
                (
                    "price_before",
                    models.DecimalField(
                        blank=True, decimal_places=0, max_digits=10, null=True
                    ),
                ),
                ("discount", models.CharField(blank=True, max_length=5, null=True)),
                ("is_after_birth", models.IntegerField(blank=True, null=True)),
                (
                    "coupon_code",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(
                        blank=True, default=datetime.datetime.now, null=True
                    ),
                ),
            ],
            options={
                "db_table": "coupons",
                "managed": False,
            },
        ),
    ]
