# Generated by Django 5.2.1 on 2025-05-17 22:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoldot", "0007_coupon"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "course_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("banner", models.CharField(max_length=255, verbose_name="Banner")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "course_description",
                    models.TextField(verbose_name="Course Description"),
                ),
                ("tags", models.JSONField(verbose_name="Tags")),
                (
                    "access_token",
                    models.CharField(max_length=255, verbose_name="Access Token"),
                ),
                ("is_free", models.BooleanField(default=False, verbose_name="Is Free")),
            ],
            options={
                "db_table": "course",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=uuid.uuid4,
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("snapshot", models.CharField(max_length=255, verbose_name="Snapshot")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("uri", models.CharField(max_length=255, verbose_name="URI")),
                ("description", models.TextField(verbose_name="Description")),
                ("duration", models.CharField(max_length=20, verbose_name="Duration")),
            ],
            options={
                "db_table": "lessons",
                "managed": False,
            },
        ),
    ]
