# Generated by Django 5.2.1 on 2025-05-17 22:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("yoldot", "0008_course_lesson"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppVersion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("platform", models.CharField(max_length=10)),
                ("version", models.CharField(max_length=10)),
                ("release_date", models.DateField(default=datetime.date)),
            ],
            options={
                "db_table": "app_versions",
                "managed": False,
            },
        ),
    ]
