from django.db import models

class Survey(models.Model):
    id = models.AutoField(primary_key=True)
    תאריך_הלידה = models.CharField(max_length=10, verbose_name="תאריך הלידה", db_column='תאריך הלידה')
    מקום_לידה = models.CharField(max_length=64, verbose_name="מקום לידה", db_column='מקום לידה')
    מספר_לידה = models.CharField(max_length=2, verbose_name="מספר לידה", db_column='מספר לידה')
    הריון_בסיכון = models.CharField(max_length=2, verbose_name="הריון בסיכון", db_column='הריון בסיכון')
    סיכון_פירוט = models.CharField(max_length=300, verbose_name="סיכון פירוט", db_column="סיכון פירוט")
    התערבויות = models.CharField(max_length=128, verbose_name="התערבויות", db_column="התערבויות")
    קיסרי_חירום = models.CharField(max_length=64, verbose_name="קיסרי חירום", db_column="קיסרי חירום")
    סוגי_זירוז = models.CharField(max_length=128, verbose_name="סוגי זירוז", db_column="סוגי זירוז")
    לווי_מיילדת = models.CharField(max_length=64, verbose_name="לווי מיילדת", db_column="לווי מיילדת")
    לווי_נוסף = models.CharField(max_length=64, verbose_name="לווי נוסף", db_column="לווי נוסף")
    כבוד = models.CharField(max_length=1, verbose_name="כבוד", db_column="כבוד")
    פרטיות_כללי = models.CharField(max_length=1, verbose_name="פרטיות כללי", db_column="פרטיות כללי")
    סגירת_דלת = models.CharField(max_length=64, verbose_name="סגירת דלת", db_column="סגירת דלת")
    סביבה_שקטה = models.CharField(max_length=1, verbose_name="סביבה שקטה", db_column="סביבה שקטה")
    דפיקה_בדלת = models.CharField(max_length=20, verbose_name="דפיקה בדלת", db_column="דפיקה בדלת")
    שרותים_ומקלחת = models.CharField(max_length=2, verbose_name="שרותים ומקלחת", db_column="שרותים ומקלחת")
    חיסיון_רפואי_אישי = models.CharField(max_length=1, verbose_name="חיסיון רפואי אישי", db_column="חיסיון רפואי אישי")
    חיסיון_רפואי_של_הסובבות = models.CharField(max_length=1, verbose_name="חיסיון רפואי של הסובבות", db_column="חיסיון רפואי של הסובבות")
    הסבר_סיכונים_סיכויים_חלופות = models.CharField(max_length=1, verbose_name="הסבר סיכונים סיכויים חלופות", db_column="הסבר סיכונים סיכויים חלופות")
    איום_והפחדה = models.CharField(max_length=2, verbose_name="איום והפחדה", db_column="איום והפחדה")
    קבלת_החלטות = models.CharField(max_length=1, verbose_name="קבלת החלטות", db_column="קבלת החלטות")
    כבוד_לבקשות_היולדת = models.CharField(max_length=1, verbose_name="כבוד לבקשות היולדת", db_column="כבוד לבקשות היולדת")
    התייחסות_לרצונות = models.CharField(max_length=1, verbose_name="התייחסות לרצונות", db_column="התייחסות לרצונות")
    סירוב_לטיפול = models.CharField(max_length=2, verbose_name="סירוב לטיפול", db_column="סירוב לטיפול")
    כיבוד_סירוב_לטיפול = models.CharField(max_length=2, verbose_name="כיבוד סירוב לטיפול", db_column="כיבוד סירוב לטיפול")
    תמיכה_רציפה = models.CharField(max_length=1, verbose_name="תמיכה רציפה", db_column="תמיכה רציפה")
    תקשורת_אפקטיבית = models.CharField(max_length=1, verbose_name="תקשורת אפקטיבית", db_column="תקשורת אפקטיבית")
    עידוד_לתנועה = models.CharField(max_length=2, verbose_name="עידוד לתנועה", db_column="עידוד לתנועה")
    אוכל_ושתיה = models.CharField(max_length=24, verbose_name="אוכל ושתיה", db_column="אוכל ושתיה")
    שיכוך_כאבים = models.CharField(max_length=2, verbose_name="שיכוך כאבים", db_column="שיכוך כאבים")
    הצעות_שיכוך_כאבים = models.CharField(max_length=256, verbose_name="הצעות שיכוך כאבים", db_column="הצעות שיכוך כאבים")
    שלב_שני = models.CharField(max_length=2, verbose_name="שלב שני", db_column="שלב שני")
    תנוחות_לידה = models.CharField(max_length=64, verbose_name="תנוחות לידה", db_column="תנוחות לידה")
    תנוחה_מועדפת = models.CharField(max_length=2, verbose_name="תנוחה מועדפת", db_column="תנוחה מועדפת")
    תחושת_דחף = models.CharField(max_length=2, verbose_name="תחושת דחף", db_column="תחושת דחף")
    תמיכה_בפרניאום = models.CharField(max_length=64, verbose_name="תמיכה בפרניאום", db_column="תמיכה בפרניאום")
    קרייסטלר = models.CharField(max_length=2, verbose_name="קרייסטלר", db_column="קרייסטלר")
    עור_לעור = models.CharField(max_length=2, verbose_name="עור לעור", db_column="עור לעור")
    הצמדה_לחזה = models.CharField(max_length=2, verbose_name="הצמדה לחזה", db_column="הצמדה לחזה")
    רחצת_תינוק = models.CharField(max_length=2, verbose_name="רחצת תינוק/ת", db_column="רחצת תינוק/ת")
    הפרדת_אם_ותינוק = models.CharField(max_length=2, verbose_name="הפרדת אם ותינוק/ת", db_column="הפרדת אם ותינוק/ת")
    סיבת_הפרדה = models.CharField(max_length=12, verbose_name="סיבת הפרדה", db_column="סיבת הפרדה")
    סיבה_אחרת_להפרדה = models.CharField(max_length=500, verbose_name="סיבה אחרת להפרדה", db_column="סיבה אחרת להפרדה")
    ביות_מלא = models.CharField(max_length=2, verbose_name="ביות מלא", db_column="ביות מלא")
    שביעות_רצון = models.CharField(max_length=1, verbose_name="שביעות רצון", db_column="שביעות רצון")
    TAGS = models.CharField(max_length=600, verbose_name="TAGS", db_column="TAGS")
    תיאור_סיפור_לידה = models.CharField(max_length=10000, verbose_name="תיאור סיפור לידה", db_column="תיאור סיפור לידה")
    הערות = models.CharField(max_length=4000, verbose_name="הערות", db_column="הערות")
    Entry_Date = models.CharField(max_length=64, verbose_name="Entry Date", db_column="Entry Date")
    אימייל = models.CharField(max_length=64, verbose_name="אימייל", db_column="אימייל")
    is_checked = models.IntegerField(verbose_name="is_checked")

    class Meta:
        db_table = 'survey_results'
        managed = False  
