from datetime import datetime
from django.db import models

class Survey(models.Model):
    id = models.AutoField(primary_key=True)
    תאריך_הלידה = models.CharField(max_length=10, verbose_name="תאריך הלידה", db_column='תאריך הלידה', blank=True, null=True)
    מקום_לידה = models.CharField(max_length=64, verbose_name="מקום לידה", db_column='מקום לידה', blank=True, null=True)
    מספר_לידה = models.CharField(max_length=2, verbose_name="מספר לידה", db_column='מספר לידה', blank=True, null=True)
    הריון_בסיכון = models.CharField(max_length=2, verbose_name="הריון בסיכון", db_column='הריון בסיכון', blank=True, null=True)
    סיכון_פירוט = models.CharField(max_length=300, verbose_name="סיכון פירוט", db_column="סיכון פירוט", blank=True, null=True)
    התערבויות = models.CharField(max_length=128, verbose_name="התערבויות", db_column="התערבויות", blank=True, null=True)
    קיסרי_חירום = models.CharField(max_length=64, verbose_name="קיסרי חירום", db_column="קיסרי חירום", blank=True, null=True)
    סוגי_זירוז = models.CharField(max_length=128, verbose_name="סוגי זירוז", db_column="סוגי זירוז", blank=True, null=True)
    לווי_מיילדת = models.CharField(max_length=64, verbose_name="לווי מיילדת", db_column="לווי מיילדת", blank=True, null=True)
    לווי_נוסף = models.CharField(max_length=64, verbose_name="לווי נוסף", db_column="לווי נוסף", blank=True, null=True)
    כבוד = models.CharField(max_length=1, verbose_name="כבוד", db_column="כבוד", blank=True, null=True)
    פרטיות_כללי = models.CharField(max_length=1, verbose_name="פרטיות כללי", db_column="פרטיות כללי", blank=True, null=True)
    סגירת_דלת = models.CharField(max_length=64, verbose_name="סגירת דלת", db_column="סגירת דלת", blank=True, null=True)
    סביבה_שקטה = models.CharField(max_length=1, verbose_name="סביבה שקטה", db_column="סביבה שקטה", blank=True, null=True)
    דפיקה_בדלת = models.CharField(max_length=20, verbose_name="דפיקה בדלת", db_column="דפיקה בדלת", blank=True, null=True)
    שרותים_ומקלחת = models.CharField(max_length=2, verbose_name="שרותים ומקלחת", db_column="שרותים ומקלחת", blank=True, null=True)
    חיסיון_רפואי_אישי = models.CharField(max_length=1, verbose_name="חיסיון רפואי אישי", db_column="חיסיון רפואי אישי", blank=True, null=True)
    חיסיון_רפואי_של_הסובבות = models.CharField(max_length=1, verbose_name="חיסיון רפואי של הסובבות", db_column="חיסיון רפואי של הסובבות", blank=True, null=True)
    הסבר_סיכונים_סיכויים_חלופות = models.CharField(max_length=1, verbose_name="הסבר סיכונים סיכויים חלופות", db_column="הסבר סיכונים סיכויים חלופות", blank=True, null=True)
    איום_והפחדה = models.CharField(max_length=2, verbose_name="איום והפחדה", db_column="איום והפחדה", blank=True, null=True)
    קבלת_החלטות = models.CharField(max_length=1, verbose_name="קבלת החלטות", db_column="קבלת החלטות", blank=True, null=True)
    כבוד_לבקשות_היולדת = models.CharField(max_length=1, verbose_name="כבוד לבקשות היולדת", db_column="כבוד לבקשות היולדת", blank=True, null=True)
    התייחסות_לרצונות = models.CharField(max_length=1, verbose_name="התייחסות לרצונות", db_column="התייחסות לרצונות", blank=True, null=True)
    סירוב_לטיפול = models.CharField(max_length=2, verbose_name="סירוב לטיפול", db_column="סירוב לטיפול", blank=True, null=True)
    כיבוד_סירוב_לטיפול = models.CharField(max_length=2, verbose_name="כיבוד סירוב לטיפול", db_column="כיבוד סירוב לטיפול", blank=True, null=True)
    תמיכה_רציפה = models.CharField(max_length=1, verbose_name="תמיכה רציפה", db_column="תמיכה רציפה", blank=True, null=True)
    תקשורת_אפקטיבית = models.CharField(max_length=1, verbose_name="תקשורת אפקטיבית", db_column="תקשורת אפקטיבית", blank=True, null=True)
    עידוד_לתנועה = models.CharField(max_length=2, verbose_name="עידוד לתנועה", db_column="עידוד לתנועה", blank=True, null=True)
    אוכל_ושתיה = models.CharField(max_length=24, verbose_name="אוכל ושתיה", db_column="אוכל ושתיה", blank=True, null=True)
    שיכוך_כאבים = models.CharField(max_length=2, verbose_name="שיכוך כאבים", db_column="שיכוך כאבים", blank=True, null=True)
    הצעות_שיכוך_כאבים = models.CharField(max_length=256, verbose_name="הצעות שיכוך כאבים", db_column="הצעות שיכוך כאבים", blank=True, null=True)
    שלב_שני = models.CharField(max_length=2, verbose_name="שלב שני", db_column="שלב שני", blank=True, null=True)
    תנוחות_לידה = models.CharField(max_length=64, verbose_name="תנוחות לידה", db_column="תנוחות לידה", blank=True, null=True)
    תנוחה_מועדפת = models.CharField(max_length=2, verbose_name="תנוחה מועדפת", db_column="תנוחה מועדפת", blank=True, null=True)
    תחושת_דחף = models.CharField(max_length=2, verbose_name="תחושת דחף", db_column="תחושת דחף", blank=True, null=True)
    תמיכה_בפרניאום = models.CharField(max_length=64, verbose_name="תמיכה בפרניאום", db_column="תמיכה בפרניאום", blank=True, null=True)
    קרייסטלר = models.CharField(max_length=2, verbose_name="קרייסטלר", db_column="קרייסטלר", blank=True, null=True)
    עור_לעור = models.CharField(max_length=2, verbose_name="עור לעור", db_column="עור לעור", blank=True, null=True)
    הצמדה_לחזה = models.CharField(max_length=2, verbose_name="הצמדה לחזה", db_column="הצמדה לחזה", blank=True, null=True)
    רחצת_תינוק = models.CharField(max_length=2, verbose_name="רחצת תינוק/ת", db_column="רחצת תינוק/ת", blank=True, null=True)
    הפרדת_אם_ותינוק = models.CharField(max_length=2, verbose_name="הפרדת אם ותינוק/ת", db_column="הפרדת אם ותינוק/ת", blank=True, null=True)
    סיבת_הפרדה = models.CharField(max_length=12, verbose_name="סיבת הפרדה", db_column="סיבת הפרדה", blank=True, null=True)
    סיבה_אחרת_להפרדה = models.CharField(max_length=500, verbose_name="סיבה אחרת להפרדה", db_column="סיבה אחרת להפרדה", blank=True, null=True)
    ביות_מלא = models.CharField(max_length=2, verbose_name="ביות מלא", db_column="ביות מלא", blank=True, null=True)
    שביעות_רצון = models.CharField(max_length=1, verbose_name="שביעות רצון", db_column="שביעות רצון", blank=True, null=True)
    TAGS = models.CharField(max_length=600, verbose_name="TAGS", db_column="TAGS", blank=True, null=True)
    תיאור_סיפור_לידה = models.CharField(max_length=10000, verbose_name="תיאור סיפור לידה", db_column="תיאור סיפור לידה", blank=True, null=True)
    הערות = models.CharField(max_length=4000, verbose_name="הערות", db_column="הערות", blank=True, null=True)
    Entry_Date = models.CharField(max_length=64, verbose_name="Entry Date", db_column="Entry Date", default=datetime.now)
    אימייל = models.CharField(max_length=64, verbose_name="אימייל", db_column="אימייל")
    is_checked = models.IntegerField(verbose_name="is_checked", default=0)

    class Meta:
        db_table = 'survey_results'
        managed = False  
